// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHfoPzaEGqaZtG7VhQvaSmBCeEJkEjjsk',
    appId: '1:1046265042842:web:345dc572862a3eeecbcc23',
    messagingSenderId: '1046265042842',
    projectId: 'weeklymenu-app-service',
    authDomain: 'weeklymenu-app-service.firebaseapp.com',
    storageBucket: 'weeklymenu-app-service.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe4QjIhJmITL6TP2kK23e5Q0_K2fUZSTM',
    appId: '1:1046265042842:android:14b32437a3239fd4cbcc23',
    messagingSenderId: '1046265042842',
    projectId: 'weeklymenu-app-service',
    storageBucket: 'weeklymenu-app-service.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkSekOkCEf6bxBeQSDdouuYMS2pujefGM',
    appId: '1:1046265042842:ios:cf6a62d816a3172ccbcc23',
    messagingSenderId: '1046265042842',
    projectId: 'weeklymenu-app-service',
    storageBucket: 'weeklymenu-app-service.firebasestorage.app',
    iosBundleId: 'com.example.weeklymenu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkSekOkCEf6bxBeQSDdouuYMS2pujefGM',
    appId: '1:1046265042842:ios:cf6a62d816a3172ccbcc23',
    messagingSenderId: '1046265042842',
    projectId: 'weeklymenu-app-service',
    storageBucket: 'weeklymenu-app-service.firebasestorage.app',
    iosBundleId: 'com.example.weeklymenu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHfoPzaEGqaZtG7VhQvaSmBCeEJkEjjsk',
    appId: '1:1046265042842:web:2723984b92c2e77acbcc23',
    messagingSenderId: '1046265042842',
    projectId: 'weeklymenu-app-service',
    authDomain: 'weeklymenu-app-service.firebaseapp.com',
    storageBucket: 'weeklymenu-app-service.firebasestorage.app',
  );
}
